language: php
before_script:
- mkdir -p testhost/plugins/
- mkdir -p testhost/web/
- mv opChatTaskPlugin testhost/plugins/opChatTaskPlugin
- cd testhost/web
- ln -s ../plugins/opChatTaskPlugin/web opChatTaskPlugin
- ln -s ../plugins/opChatTaskPlugin/test/QUnit/test.php test.php
- cd ../../
- php testhost/web/test.php > testhost/web/test.html
script:
- phantomjs testhost/plugins/opChatTaskPlugin/test/QUnit/phantom-qunit.js testhost/web/test.html
