language: php
before_script:
- mkdir localhost
- mv opChatTaskPlugin localhost/
- php localhost/opChatTaskPlugin/test/QUnit/test.php > localhost/test.html
script:
- phantomjs localhost/opChatTaskPlugin/test/QUnit/phantom-qunit.js test.html
